spring.application.name=product-management-api

spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=postgres
spring.datasource.password=admin12#
spring.jpa.hibernate.ddl-auto=update